title = "中正資工 機器視覺與學習實驗室"
baseURL = "https://example.com"
languageCode = "en-us"
theme = ""


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "CCU Machine Vision and Learning Lab"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = "https://www.youtube.com/?gl=TW&hl=zh-tw"
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/header-bg.jpg"
  recent_posts_number = 2
  
